use_frameworks!

platform :ios, '8.0'

target 'EYCountDownButton_Example' do
  pod 'EYCountDownButton', :path => '../'

  target 'EYCountDownButton_Tests' do
    inherit! :search_paths

    
  end
end
